import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[2]


class TestPARSegHCEScaffold(unittest.TestCase):

    def test_hce_head_defines_learned_latent_confusion_router(self):
        head = (ROOT / "mmseg/models/decode_heads/PARSegHCE.py").read_text(encoding="utf-8")

        self.assertIn("class LearnedConfusionRouter", head)
        self.assertIn("class CandidateMaskedExpert", head)
        self.assertIn("class PARSegHCE(PARSeg3)", head)

        # HCE-v2 must be a method, not an ADE20K/PARSeg3 failure patch:
        # no hand-coded confusion groups, no dataset-specific constants,
        # and no group file generated by a pretrained model.
        self.assertNotIn("DEFAULT_ADE20K_GROUPS", head)
        self.assertNotIn("hce_groups", head)
        self.assertNotIn("hce_group_file", head)
        self.assertNotIn("group_delta[:, group", head)

        # The confusion structure is learned end-to-end from class relation
        # tokens and current logits, then applied as a candidate mask.
        self.assertIn("self.class_tokens", head)
        self.assertIn("def relation_matrix", head)
        self.assertIn("torch.einsum('bihw,ij->bjhw'", head)
        self.assertIn("candidate_topk", head)

        # The residual should be candidate-masked, not entropy-suppressed:
        # PARSeg3's observed errors include many confident-wrong pixels, so
        # base entropy must not be used as a multiplicative correction gate.
        self.assertIn("masked_delta = delta_logits * candidate_weights", head)
        self.assertNotIn("candidate_weights * uncertainty", head)
        self.assertNotIn("hce_uncertainty", head)
        self.assertIn("base_head_logits = raw_base_head_logits + self._hce_gate() * masked_delta", head)

        # init-safe gate, same idiom as every other head in this repo.
        self.assertIn("self.hce_gate_max = gate_max", head)
        self.assertIn("self.hce_gate_max * torch.sigmoid(self.hce_alpha)", head)

        # Training is supervised by ordinary segmentation losses plus a
        # lightweight sparsity regularizer; no pretrained confusion labels.
        self.assertIn("loss_hce_sparsity", head)
        self.assertNotIn("loss_hce_aux", head)

    def test_hce_config_is_from_scratch_end_to_end_method(self):
        cfg = (ROOT / "local_configs/offseg2/Base/parseghce_ade20k_160k-512x512.py").read_text(encoding="utf-8")

        self.assertIn("mmseg.models.decode_heads.PARSegHCE", cfg)
        self.assertIn("type='PARSegHCE'", cfg)
        self.assertIn("hce_relation_dim=64", cfg)
        self.assertIn("hce_candidate_topk=8", cfg)
        self.assertIn("hce_sparsityw=0.02", cfg)

        # No PARSeg3 checkpoint, no precomputed confusion matrix, no
        # dataset-specific manual group list.
        self.assertNotIn("load_from", cfg)
        self.assertNotIn("hce_groups", cfg)
        self.assertNotIn("hce_group_file", cfg)
        self.assertNotIn("iter_160000.pth", cfg)


if __name__ == "__main__":
    unittest.main()
