# -*- coding: utf-8 -*-
"""ADE20K-150 per-class attribute descriptions (6 per class).

Written for PARSeg-PAT: grounding PAL attribute tokens in language-described
attributes. Style rules (deliberate):
  * pure attribute phrases -- material / shape-geometry / position /
    function / context / appearance detail (one each, roughly);
  * NO negation and NO explicit "unlike X" contrast: CLIP encodes negation
    unreliably, and explicit contrast would contaminate the attribute
    content. Discriminativeness comes from attribute specificity only.
  * class NAMES are not required to appear in the description; the point is
    attribute content, not name geometry (the name-cone failure, see
    experiment log).
Reviewable/editable by hand; consumed by tools/gen_text_descriptions.py.
"""

DESCRIPTIONS = {
    "wall": [
        "flat vertical painted plaster surface",
        "large upright surface bounding a room",
        "smooth solid surface meeting the ceiling at a corner",
        "surface that pictures and shelves hang on",
        "painted interior surface above a baseboard",
        "uniform matte surface between floor and ceiling",
    ],
    "building": [
        "exterior facade with rows of windows",
        "tall man-made structure of concrete or brick",
        "multi-story block seen from the street",
        "structure housing offices or apartments",
        "urban architecture with doors and balconies",
        "masonry exterior with repeated window openings",
    ],
    "sky": [
        "bright open expanse above the horizon",
        "smooth gradient of blue or grey overhead",
        "region with clouds and daylight",
        "backdrop behind rooftops and treetops",
        "airy empty space above the scene",
        "hazy luminous area at the top of an outdoor view",
    ],
    "floor": [
        "flat horizontal walked-on surface indoors",
        "wooden boards or tiles underfoot",
        "level surface furniture stands on",
        "polished horizontal plane at the bottom of a room",
        "surface with rugs and chair legs resting on it",
        "smooth ground plane inside a building",
    ],
    "tree": [
        "tall plant with a woody trunk and leafy crown",
        "branching foliage mass on a single stem",
        "green canopy with rough bark below",
        "outdoor plant casting dappled shade",
        "leaves and branches swaying above a lawn",
        "trunk rising into a rounded crown of leaves",
    ],
    "ceiling": [
        "flat overhead surface of a room",
        "white plaster plane above the walls",
        "surface that light fixtures hang from",
        "horizontal surface seen when looking up indoors",
        "smooth painted plane above furniture",
        "overhead surface with recessed lights or beams",
    ],
    "road": [
        "wide asphalt surface for vehicles",
        "paved carriageway with lane markings",
        "dark tarmac stretching toward the horizon",
        "driving surface with painted center lines",
        "smooth pavement carrying cars and buses",
        "broad paved strip between curbs",
    ],
    "bed ": [
        "rectangular mattress with pillows and covers",
        "sleeping furniture with a headboard",
        "soft padded platform draped in blankets",
        "bedroom furniture for lying down",
        "quilted surface with folded linens",
        "low wide furniture piece topped with sheets",
    ],
    "windowpane": [
        "glass sheet set in a window frame",
        "transparent pane letting daylight in",
        "reflective glazing within a sash",
        "see-through panel in an exterior wall opening",
        "glass surface with mullions dividing it",
        "framed transparent opening showing the outdoors",
    ],
    "grass": [
        "short green blades covering the ground",
        "mowed lawn with fine texture",
        "soft green ground cover outdoors",
        "turf spreading across a yard or park",
        "dense low vegetation carpeting soil",
        "fresh green sward with a fine even texture",
    ],
    "cabinet": [
        "boxy storage furniture with doors",
        "wooden cupboard with shelves inside",
        "kitchen unit with hinged panel fronts",
        "enclosed storage with knobs or handles",
        "rectangular casework mounted along a wall",
        "furniture with flat door panels concealing storage",
    ],
    "sidewalk": [
        "narrow paved path beside a road",
        "concrete walkway with expansion joints",
        "pedestrian pavement along storefronts",
        "light grey footpath bordered by a curb",
        "walking strip separated from traffic",
        "paved pedestrian lane with seams and cracks",
    ],
    "person": [
        "upright human figure with head and limbs",
        "clothed body walking or standing",
        "pedestrian with visible face and hair",
        "human silhouette in motion",
        "someone wearing everyday clothes",
        "figure with arms, legs and a head",
    ],
    "earth": [
        "bare soil with an uneven crumbly texture",
        "brown dirt ground without vegetation",
        "exposed loam or mud surface",
        "natural unpaved ground outdoors",
        "dusty terrain with small stones",
        "raw ground of packed soil",
    ],
    "door": [
        "hinged rectangular panel with a handle",
        "swinging wooden slab set in a frame",
        "entry panel with a knob and keyhole",
        "tall narrow panel that opens a passage",
        "paneled leaf within a doorway casing",
        "movable barrier at a room entrance",
    ],
    "table": [
        "flat horizontal top on legs",
        "furniture surface for meals or work",
        "wooden slab standing at waist height",
        "surface holding plates, books or lamps",
        "four-legged furniture with a broad top",
        "raised platform people sit around",
    ],
    "mountain": [
        "massive rocky landform rising steeply",
        "distant peak with ridges and slopes",
        "high rugged terrain against the sky",
        "steep natural elevation with exposed rock",
        "towering landmass with a summit",
        "sloped highland with snow or scree",
    ],
    "plant": [
        "leafy green vegetation in a pot or bed",
        "houseplant with stems and broad leaves",
        "low ornamental foliage",
        "cluster of green leaves growing from soil",
        "potted greenery decorating a room",
        "small shrub with dense leaves",
    ],
    "curtain": [
        "hanging fabric panel beside a window",
        "soft drapery falling in vertical folds",
        "cloth screen that slides on a rail",
        "textile panel filtering window light",
        "long pleated fabric from rod to floor",
        "flowing window covering of cloth",
    ],
    "chair": [
        "single seat with a backrest",
        "four-legged furniture for one sitter",
        "seat with armrests and a back",
        "compact furniture pulled up to a table",
        "upright seat with a padded cushion",
        "small movable seat with slender legs",
    ],
    "car": [
        "four-wheeled passenger vehicle",
        "sedan with windshield and headlights",
        "glossy metal body on rubber tires",
        "automobile parked along the street",
        "compact motor vehicle with side doors",
        "vehicle with side mirrors and license plate",
    ],
    "water": [
        "liquid surface with ripples and reflections",
        "shimmering expanse of a lake or pool",
        "flowing or still clear liquid",
        "reflective sheet broken by small waves",
        "cool blue surface of a pond or river",
        "wet glinting surface under open sky",
    ],
    "painting": [
        "framed artwork hanging on a wall",
        "rectangular canvas with brushwork",
        "decorative picture in a frame",
        "wall-mounted art print or oil piece",
        "colorful image bounded by a wooden frame",
        "flat art piece displayed indoors",
    ],
    "sofa": [
        "long upholstered seat for several people",
        "cushioned couch with padded armrests",
        "deep soft seating with throw pillows",
        "fabric-covered lounge furniture",
        "wide low seat with a full backrest",
        "plush multi-seat couch in a living room",
    ],
    "shelf": [
        "horizontal board holding items",
        "open ledge mounted on a wall",
        "flat storage plank in a rack",
        "surface lined with books or objects",
        "thin horizontal panel fixed at height",
        "open storage tier without doors",
    ],
    "house": [
        "small residential building with a pitched roof",
        "detached home with windows and a front door",
        "dwelling with chimney and eaves",
        "single-family residence seen from outside",
        "cozy building with a porch and yard",
        "low residential structure with siding",
    ],
    "sea": [
        "vast open water reaching the horizon",
        "blue expanse with rolling waves",
        "salt water surface with whitecaps",
        "endless ocean under the sky",
        "large body of water beyond a shoreline",
        "swelling marine surface with foam",
    ],
    "mirror": [
        "reflective glass showing the room",
        "silvered surface in a frame",
        "shiny panel duplicating what faces it",
        "wall glass with a crisp reflection",
        "polished reflective oval or rectangle",
        "glass revealing a reversed image",
    ],
    "rug": [
        "soft woven mat lying on the floor",
        "patterned carpet piece with fringed edges",
        "thick textile covering part of the floor",
        "decorative floor cloth under furniture",
        "bordered soft rectangle on the floorboards",
        "plush area carpet with printed motifs",
    ],
    "field": [
        "wide open stretch of low vegetation",
        "flat farmland or meadow",
        "broad grassy plain outdoors",
        "cultivated land reaching the tree line",
        "expansive level ground with crops or grass",
        "open rural acreage under the sky",
    ],
    "armchair": [
        "single padded seat with thick armrests",
        "upholstered chair with a cushioned back",
        "deep comfortable seat for one person",
        "stuffed chair with supportive arms",
        "cozy fabric seat with rounded arms",
        "plush single seat with high padded sides",
    ],
    "seat": [
        "bench-like place for sitting",
        "fixed sitting surface in a public space",
        "padded or wooden sitting ledge",
        "row seating in a hall or vehicle",
        "simple platform for a person to sit",
        "sitting spot with a flat cushion",
    ],
    "fence": [
        "row of posts and rails marking a boundary",
        "wooden or metal barrier around a yard",
        "repeating slats enclosing an area",
        "openwork barrier along a property line",
        "low protective railing of pickets",
        "linked panels forming a perimeter",
    ],
    "desk": [
        "work table with drawers",
        "flat writing surface with storage below",
        "office furniture holding a computer",
        "sturdy table used for study",
        "workstation top with pens and papers",
        "rectangular work surface at sitting height",
    ],
    "rock": [
        "hard grey stone mass with rough texture",
        "boulder with jagged weathered faces",
        "solid mineral lump on the ground",
        "craggy stone outcrop",
        "heavy angular chunk of rock",
        "coarse stone surface with cracks",
    ],
    "wardrobe": [
        "tall cabinet for hanging clothes",
        "large bedroom cupboard with full doors",
        "upright closet furniture with a rail inside",
        "clothes storage with long door panels",
        "freestanding tall storage for garments",
        "bedroom armoire with hinged doors",
    ],
    "lamp": [
        "light fixture with a shade on a stand",
        "glowing bulb under a fabric shade",
        "table light with a slender stem",
        "warm light source beside a sofa",
        "decorative fixture casting local light",
        "upright pole topped with a light",
    ],
    "bathtub": [
        "deep white basin for bathing",
        "long ceramic tub with a faucet",
        "smooth curved vessel holding bath water",
        "bathroom fixture large enough to lie in",
        "glossy enamel tub with a drain",
        "oval basin beside tiled walls",
    ],
    "railing": [
        "waist-high protective bar along an edge",
        "row of balusters topped by a handrail",
        "metal or wooden guard beside stairs",
        "open barrier along a balcony rim",
        "slim rail for gripping while climbing steps",
        "protective handhold along a walkway drop",
    ],
    "cushion": [
        "soft square pillow on a seat",
        "plump fabric pad with piped edges",
        "decorative throw pillow",
        "stuffed textile square resting on a sofa",
        "squeezable padded accessory",
        "small soft bolster for comfort",
    ],
    "base": [
        "supporting pedestal under a column or statue",
        "solid plinth at the bottom of a structure",
        "wide footing block bearing weight",
        "stone or concrete mounting platform",
        "lowest supporting tier of an object",
        "sturdy foundation block under a monument",
    ],
    "box": [
        "rectangular container with straight sides",
        "cardboard carton with folded flaps",
        "cubic storage bin",
        "small crate holding loose items",
        "sealed rectangular package",
        "stackable container with a lid",
    ],
    "column": [
        "tall vertical cylindrical support",
        "round load-bearing pillar",
        "slender upright shaft holding a roof",
        "fluted stone post between floor and ceiling",
        "freestanding vertical structural member",
        "smooth pillar with a capital on top",
    ],
    "signboard": [
        "flat panel with lettering or symbols",
        "mounted sign displaying text",
        "storefront board with a printed name",
        "informational placard on a pole",
        "rectangular display with painted words",
        "advertising panel fixed above a shop",
    ],
    "chest of drawers": [
        "low wide cabinet of stacked drawers",
        "bedroom dresser with pull handles",
        "furniture with sliding storage tiers",
        "multiple stacked drawers in a wooden frame",
        "storage chest with rows of knobs",
        "waist-high dresser topped by trinkets",
    ],
    "counter": [
        "long service surface at standing height",
        "flat worktop where customers are served",
        "extended bar-like tabletop",
        "smooth continuous surface in a shop or cafe",
        "elongated hard top for transactions",
        "service ledge separating staff and guests",
    ],
    "sand": [
        "fine pale grains covering the ground",
        "loose beige granular surface",
        "soft beach ground with ripples",
        "dry powdery terrain with footprints",
        "tiny mineral grains forming dunes",
        "granular tan ground near water",
    ],
    "sink": [
        "basin with a faucet for washing",
        "ceramic or steel bowl with a drain",
        "kitchen or bathroom washing fixture",
        "recessed basin set into a countertop",
        "water basin with taps above it",
        "shallow bowl fixture with running water",
    ],
    "skyscraper": [
        "extremely tall glass office tower",
        "high-rise with a curtain-wall facade",
        "slender building dominating the skyline",
        "towering structure of steel and glass",
        "landmark tower with dozens of floors",
        "vertical urban giant reflecting the sky",
    ],
    "fireplace": [
        "recessed hearth for an open fire",
        "brick or stone alcove with a mantel",
        "sooty firebox framed by a surround",
        "indoor hearth with logs and flames",
        "chimney opening in a living-room wall",
        "warm glowing alcove under a mantelpiece",
    ],
    "refrigerator": [
        "tall kitchen appliance with sealed doors",
        "boxy cooler with a freezer compartment",
        "glossy upright food-storage appliance",
        "humming appliance keeping food cold",
        "large white or steel kitchen unit",
        "double-door appliance with magnets on it",
    ],
    "grandstand": [
        "tiered rows of spectator seating",
        "stepped bleachers facing a field",
        "large angled stand full of seats",
        "stadium seating structure",
        "ascending benches for a crowd",
        "sloped seating bank at a sports ground",
    ],
    "path": [
        "narrow unpaved walking trail",
        "dirt or gravel track through greenery",
        "winding footway in a garden",
        "trodden route across a park",
        "informal lane for walking",
        "meandering strip of bare ground",
    ],
    "stairs": [
        "flight of steps rising between levels",
        "series of treads and risers",
        "ascending stone or wooden steps",
        "staircase climbing to another floor",
        "stepped incline with even spacing",
        "stacked horizontal treads going up",
    ],
    "runway": [
        "long wide airstrip with markings",
        "flat paved strip for aircraft",
        "airport tarmac with painted numbers",
        "broad takeoff lane with centerline",
        "expansive concrete strip for landing",
        "straight open pavement for planes",
    ],
    "case": [
        "glass display cabinet for exhibits",
        "transparent showcase protecting items",
        "vitrine with objects on display",
        "shop counter case with a glass top",
        "enclosed exhibit box in a museum",
        "clear-sided cabinet for valuables",
    ],
    "pool table": [
        "green felt table with pockets",
        "billiard table with rails and balls",
        "rectangular gaming table with cues",
        "cloth-covered slate table for pool",
        "table with six pockets and colored balls",
        "recreation table with a smooth green top",
    ],
    "pillow": [
        "soft rectangular cushion for the head",
        "fluffy bed pillow in a cotton case",
        "plump sleeping cushion",
        "cushiony headrest on a mattress",
        "stuffed soft block at the bed head",
        "squashy white pillow with a seam",
    ],
    "screen door": [
        "door with a mesh panel",
        "light frame door letting air through",
        "secondary door of fine netting",
        "hinged frame holding a woven screen",
        "breezy mesh entry panel",
        "see-through insect door on a porch",
    ],
    "stairway": [
        "full staircase with handrails",
        "enclosed run of steps between floors",
        "sweeping stairs with a banister",
        "climbing passage of repeated steps",
        "wide formal steps ascending indoors",
        "staircase turning at a landing",
    ],
    "river": [
        "wide flowing watercourse between banks",
        "moving fresh water winding through land",
        "broad stream with visible current",
        "waterway crossed by bridges",
        "gliding surface bordered by shores",
        "long natural channel of flowing water",
    ],
    "bridge": [
        "elevated span crossing water or a road",
        "structure with piers and a deck",
        "arched crossing over a river",
        "suspended roadway between banks",
        "long span carrying traffic overhead",
        "engineered crossing with railings",
    ],
    "bookcase": [
        "tall shelving filled with books",
        "open wooden case of stacked shelves",
        "library furniture holding rows of spines",
        "upright bookshelf with many tiers",
        "wall unit lined with volumes",
        "shelving tower crowded with books",
    ],
    "blind": [
        "horizontal slats covering a window",
        "adjustable louvered window shade",
        "venetian slats on a cord",
        "layered thin strips blocking light",
        "window covering of parallel slats",
        "pull-cord shade with tilting slats",
    ],
    "coffee table": [
        "low table in front of a sofa",
        "knee-height living-room table",
        "small flat table for cups and magazines",
        "central low top between seats",
        "compact rectangular lounge table",
        "short-legged table on a rug",
    ],
    "toilet": [
        "white ceramic bowl with a seat and lid",
        "porcelain fixture with a flush tank",
        "bathroom bowl with a hinged seat",
        "compact sanitary fixture near tiles",
        "glossy white pedestal bowl",
        "water closet with a push-button tank",
    ],
    "flower": [
        "colorful petaled blossom on a stem",
        "bright bloom with delicate petals",
        "flowering head in a garden or vase",
        "vivid petals around a center",
        "fresh blossom among green leaves",
        "small radiant bloom with soft petals",
    ],
    "book": [
        "bound pages with a printed cover",
        "closed volume with a visible spine",
        "paper stack bound into a cover",
        "readable object with title lettering",
        "hardcover or paperback lying flat",
        "stacked printed volumes",
    ],
    "hill": [
        "gentle rounded rise of land",
        "low grassy elevation",
        "soft sloped mound on the horizon",
        "modest natural bump in the terrain",
        "rolling rise covered in vegetation",
        "smooth low summit under open sky",
    ],
    "bench": [
        "long seat for several people outdoors",
        "wooden slatted seat with legs",
        "park seat with a backrest",
        "sturdy elongated public seat",
        "simple plank seating along a path",
        "weathered outdoor seat for resting",
    ],
    "countertop": [
        "flat kitchen work surface",
        "stone or laminate worktop over cabinets",
        "smooth hard surface for food preparation",
        "continuous kitchen slab with a sink cutout",
        "polished granite work surface",
        "clean flat surface holding appliances",
    ],
    "stove": [
        "cooking appliance with burners",
        "kitchen range with knobs and grates",
        "hot cooktop with rings or flames",
        "appliance for boiling and frying",
        "enameled cooker with an oven below",
        "burner surface with control dials",
    ],
    "palm": [
        "tropical tree with fan-like fronds",
        "tall bare trunk topped by long leaves",
        "arching feathery fronds on a slim stem",
        "coastal tree with a leafy crown",
        "exotic tree with radiating leaves",
        "slender trunk crowned by drooping fronds",
    ],
    "kitchen island": [
        "freestanding counter block in a kitchen",
        "central cabinet unit with a worktop",
        "detached kitchen surface with stools",
        "boxy mid-room counter with storage",
        "standalone prep surface with a sink",
        "central island bench for cooking",
    ],
    "computer": [
        "desktop machine with a monitor and keyboard",
        "screen and tower on a desk",
        "electronic workstation with a display",
        "device with a glowing screen and mouse",
        "office machine for typing and work",
        "monitor paired with input devices",
    ],
    "swivel chair": [
        "office chair rotating on a central post",
        "wheeled desk chair with a lever",
        "padded task chair on caster wheels",
        "adjustable rolling seat with armrests",
        "spinning chair with a five-star base",
        "ergonomic desk seat on wheels",
    ],
    "boat": [
        "small watercraft floating on the surface",
        "hull with a bow and stern",
        "vessel moored at a dock",
        "open craft with seats and oars",
        "buoyant hull rocking on waves",
        "compact ship with a deck rail",
    ],
    "bar": [
        "long counter where drinks are served",
        "high serving surface with stools in front",
        "polished counter with bottles behind",
        "tavern surface lined with taps",
        "elevated drink counter with a footrest",
        "service counter under hanging glasses",
    ],
    "arcade machine": [
        "upright gaming cabinet with a screen",
        "coin-operated machine with a joystick",
        "glowing game box with buttons",
        "boxy amusement machine with artwork",
        "video game cabinet with a marquee",
        "electronic entertainment console cabinet",
    ],
    "hovel": [
        "small crude hut of rough materials",
        "makeshift shack with a sagging roof",
        "ramshackle shelter of boards and tin",
        "tiny dilapidated dwelling",
        "improvised hut with patched walls",
        "weathered shanty leaning to one side",
    ],
    "bus": [
        "long public transit vehicle with many windows",
        "large boxy coach carrying passengers",
        "city vehicle with route numbers displayed",
        "extended vehicle with double doors",
        "high-roofed passenger transport",
        "wide road vehicle with rows of seats",
    ],
    "towel": [
        "soft absorbent cloth hung to dry",
        "terry fabric folded on a rail",
        "fluffy rectangle for drying hands",
        "cotton drying cloth in a bathroom",
        "looped-pile fabric draped on a hook",
        "plush cloth beside a sink",
    ],
    "light": [
        "glowing fixture mounted overhead",
        "bright bulb casting illumination",
        "ceiling light spreading a warm glow",
        "small luminous source on a wall",
        "shining lamp point in the scene",
        "electric fixture radiating light",
    ],
    "truck": [
        "heavy vehicle with a large cargo body",
        "high-cab hauler with big wheels",
        "boxy freight vehicle",
        "utility vehicle with an open or closed bed",
        "large road machine for transporting goods",
        "rugged vehicle with a tall grille",
    ],
    "tower": [
        "tall slender freestanding structure",
        "narrow high landmark with a small top",
        "vertical spire rising above rooftops",
        "lofty structure for observation or signals",
        "slim towering construction",
        "high pillar-like building",
    ],
    "chandelier": [
        "ornate hanging fixture with many lights",
        "branched ceiling light with crystals",
        "decorative suspended candelabra",
        "sparkling multi-arm ceiling lamp",
        "elegant fixture dangling above a hall",
        "tiered hanging lights with pendants",
    ],
    "awning": [
        "fabric canopy projecting over a storefront",
        "sloped cloth shade above a window",
        "striped overhang sheltering an entrance",
        "retractable canvas roof extension",
        "shop-front shade of stretched fabric",
        "angled textile cover over a doorway",
    ],
    "streetlight": [
        "tall pole topped with a road lamp",
        "curved arm light over the pavement",
        "public lighting mast along a street",
        "high lamp standard beside the road",
        "metal pole with a glowing head",
        "roadside pole light on a concrete base",
    ],
    "booth": [
        "small enclosed stall for one person",
        "compact kiosk with a window",
        "partitioned cubicle in a public space",
        "tiny freestanding service enclosure",
        "boxed-in stand with a counter slot",
        "snug enclosed seating or service nook",
    ],
    "television receiver": [
        "flat screen displaying moving images",
        "wide dark panel mounted or on a stand",
        "glowing display for shows and films",
        "rectangular screen with thin bezels",
        "living-room display with remote control",
        "large video screen on a console",
    ],
    "airplane": [
        "winged aircraft with a fuselage",
        "jet with engines under the wings",
        "streamlined flying machine with a tail fin",
        "passenger plane on the tarmac",
        "metal aircraft with a cockpit windshield",
        "long tube body with swept wings",
    ],
    "dirt track": [
        "unpaved earthen route with tire marks",
        "rutted brown trail for vehicles",
        "loose-surface track of packed soil",
        "dusty path worn by wheels",
        "rough terrain lane without pavement",
        "bare ground strip with grooves",
    ],
    "apparel": [
        "garments displayed or draped",
        "folded or hanging clothing items",
        "fabric wear like shirts and coats",
        "clothes arranged on racks",
        "textile garments in a pile or on hangers",
        "assorted clothing pieces",
    ],
    "pole": [
        "thin vertical rod fixed in the ground",
        "slender upright shaft of metal or wood",
        "narrow mast holding signs or wires",
        "tall skinny cylindrical post",
        "single upright stick-like support",
        "minimal vertical rod in the street",
    ],
    "land": [
        "open ground surface without pavement",
        "broad natural terrain",
        "expanse of soil and sparse growth",
        "undeveloped stretch of ground",
        "raw open terrain under the sky",
        "wide natural ground area",
    ],
    "bannister": [
        "sloping handrail beside a staircase",
        "polished rail following the steps",
        "stair rail supported by spindles",
        "smooth rounded handhold going down",
        "inclined railing along a stairway",
        "wood or metal rail atop balusters",
    ],
    "escalator": [
        "moving staircase with metal steps",
        "motorized diagonal stairway",
        "ridged steps gliding upward",
        "automatic stairs with rubber handrails",
        "inclined conveyor of steps",
        "mechanical staircase in a mall",
    ],
    "ottoman": [
        "low upholstered footstool",
        "cushioned block for resting feet",
        "soft backless padded seat",
        "square plush rest in front of a chair",
        "fabric-covered low stool",
        "compact padded platform seat",
    ],
    "bottle": [
        "narrow-necked container for liquid",
        "glass or plastic vessel with a cap",
        "slender container with a label",
        "corked or capped liquid holder",
        "translucent vessel with a narrow spout",
        "upright drink container",
    ],
    "buffet": [
        "long low sideboard for serving dishes",
        "dining-room cabinet with a serving top",
        "wide credenza holding platters",
        "low storage furniture for tableware",
        "serving counter with cabinets below",
        "elongated sideboard against a wall",
    ],
    "poster": [
        "printed sheet fixed to a wall",
        "large paper advertisement",
        "colorful promotional print",
        "unframed graphic sheet with imagery",
        "glossy printed page displayed publicly",
        "flat paper artwork taped up",
    ],
    "stage": [
        "raised platform for performances",
        "elevated floor facing an audience",
        "performance deck with curtains",
        "spotlit platform in a hall",
        "broad riser for performers",
        "front platform under stage lights",
    ],
    "van": [
        "boxy enclosed vehicle with sliding doors",
        "tall compact cargo vehicle",
        "family or delivery vehicle with a high roof",
        "windowed box-shaped automobile",
        "medium road vehicle with rear doors",
        "utility vehicle with an enclosed body",
    ],
    "ship": [
        "large seagoing vessel with a superstructure",
        "big hull with decks and masts",
        "ocean craft with a bridge tower",
        "massive floating vessel at sea",
        "long steel hull with portholes",
        "heavy watercraft with a funnel",
    ],
    "fountain": [
        "ornamental structure spraying water",
        "basin with jets arcing upward",
        "sculpted centerpiece with falling water",
        "plaza feature bubbling with spray",
        "tiered stone bowl overflowing water",
        "decorative water jets in a pool",
    ],
    "conveyer belt": [
        "moving rubber band carrying items",
        "long motorized transport strip",
        "rolling belt over metal rollers",
        "continuous loop moving objects along",
        "industrial belt line with side guards",
        "flat moving surface in a terminal",
    ],
    "canopy": [
        "overhead fabric or rigid cover",
        "suspended shelter above an entrance",
        "wide protective roof-like cover",
        "stretched sheet providing shade",
        "elevated covering over a walkway",
        "sheltering top supported by posts",
    ],
    "washer": [
        "front-loading laundry machine with a round door",
        "white appliance with a porthole window",
        "drum machine for washing clothes",
        "boxy laundry appliance with dials",
        "spinning-drum washing appliance",
        "utility machine with a circular glass door",
    ],
    "plaything": [
        "colorful toy for children",
        "small plastic plaything on the floor",
        "stuffed or molded toy object",
        "bright play item in a kids room",
        "cheerful toy with rounded shapes",
        "small object made for play",
    ],
    "swimming pool": [
        "rectangular basin of clear blue water",
        "tiled pool with lane lines or a ladder",
        "turquoise man-made water basin",
        "outdoor pool with a smooth deck edge",
        "chlorinated water enclosure for swimming",
        "flat blue water surface with coping",
    ],
    "stool": [
        "backless seat on tall legs",
        "simple round seat without arms",
        "high perch seat at a counter",
        "compact legged seat with a flat top",
        "minimal seat of wood or metal",
        "small circular seat on slim legs",
    ],
    "barrel": [
        "rounded wooden cask with metal hoops",
        "cylindrical container with staves",
        "bulging storage drum",
        "stout keg standing upright",
        "banded cask for liquids",
        "large round-bellied container",
    ],
    "basket": [
        "woven container with an open top",
        "wicker vessel with a handle",
        "latticed carrier of reeds or wire",
        "handwoven storage bowl",
        "openwork container for carrying goods",
        "braided container with a curved rim",
    ],
    "waterfall": [
        "water plunging over a rocky ledge",
        "white cascade dropping down a cliff",
        "vertical stream of falling water",
        "misty torrent tumbling over stone",
        "foaming water descending in sheets",
        "natural cascade with spray at its base",
    ],
    "tent": [
        "fabric shelter with sloped sides",
        "pitched canvas dome or ridge shelter",
        "portable camping enclosure with guy lines",
        "zippered fabric dwelling outdoors",
        "taut sheet shelter staked to the ground",
        "lightweight temporary fabric structure",
    ],
    "bag": [
        "soft carrier with handles or straps",
        "fabric or leather pouch for belongings",
        "slouchy container carried by hand",
        "zipped or open-top personal carrier",
        "flexible sack with a shoulder strap",
        "portable holdall of cloth or leather",
    ],
    "minibike": [
        "small two-wheeled motor vehicle",
        "compact motorcycle with a low seat",
        "light scooter-like bike with an engine",
        "small-framed motorbike",
        "nimble little motorized two-wheeler",
        "short motorbike with small wheels",
    ],
    "cradle": [
        "small rocking bed for an infant",
        "curved baby cot on rockers",
        "tiny enclosed sleeping berth for a baby",
        "gently swaying infant bed",
        "low slatted baby bed with bedding",
        "nursery bed with rounded rails",
    ],
    "oven": [
        "enclosed heated box for baking",
        "kitchen appliance with a drop-down door",
        "hot chamber with racks inside",
        "built-in baking compartment with a glass door",
        "cooking cavity with temperature dials",
        "radiant appliance for roasting",
    ],
    "ball": [
        "round object for games",
        "smooth sphere of rubber or leather",
        "bouncing spherical toy",
        "single round play object",
        "uniform sphere with seams or panels",
        "rollable round item on the ground",
    ],
    "food": [
        "prepared dishes arranged for eating",
        "colorful edible items on plates",
        "cooked meal portions",
        "fresh ingredients and servings",
        "appetizing spread on a table",
        "assorted edible items close up",
    ],
    "step": [
        "single low platform to step on",
        "one shallow stair at a threshold",
        "small raised ledge underfoot",
        "short rise between two levels",
        "low concrete or stone tread",
        "single elevation change at an entrance",
    ],
    "tank": [
        "large storage vessel for liquid or gas",
        "cylindrical industrial container",
        "big sealed reservoir with pipes",
        "bulky metal holding vessel",
        "round-walled storage drum outdoors",
        "utility container of welded steel",
    ],
    "trade name": [
        "brand lettering mounted on a building",
        "illuminated shop name sign",
        "logo text above a storefront",
        "commercial brand mark on a facade",
        "large stylized lettering of a business",
        "raised channel letters spelling a name",
    ],
    "microwave": [
        "countertop appliance with a hinged door",
        "compact box oven with a keypad",
        "small appliance with a turntable inside",
        "kitchen box with a window and buttons",
        "quick-heating enclosed appliance",
        "boxy device with a digital timer",
    ],
    "pot": [
        "deep round cooking vessel with handles",
        "planting container of clay or ceramic",
        "sturdy cylindrical vessel",
        "lidded cooking vessel on a stove",
        "earthen or metal rounded container",
        "wide-mouthed vessel for plants or food",
    ],
    "animal": [
        "living creature with fur or feathers",
        "four-legged beast in the scene",
        "domestic or wild creature",
        "moving creature with a tail",
        "furry or feathered living being",
        "non-human creature standing or walking",
    ],
    "bicycle": [
        "pedal-driven two-wheeler with handlebars",
        "slim frame with spoked wheels",
        "human-powered cycle with a chain",
        "leaning two-wheeler with a saddle",
        "light vehicle with pedals and a bell",
        "wire-wheeled cycle parked or ridden",
    ],
    "lake": [
        "large still body of fresh water",
        "calm inland water with reflections",
        "broad placid water ringed by shore",
        "mirror-like natural water expanse",
        "quiet water body surrounded by land",
        "wide smooth freshwater surface",
    ],
    "dishwasher": [
        "under-counter appliance with a drop door",
        "kitchen machine with racks for dishes",
        "built-in washing appliance for tableware",
        "front-panel appliance beside the sink",
        "enclosed dish-cleaning machine",
        "stainless appliance with a control strip",
    ],
    "screen": [
        "folding upright partition panel",
        "freestanding room divider",
        "projection surface or display panel",
        "flat panel separating spaces",
        "portable divider of framed panels",
        "wide upright panel for display or privacy",
    ],
    "blanket": [
        "soft warm covering spread on a bed",
        "thick woven throw draped over furniture",
        "cozy fabric layer for warmth",
        "folded fleece or wool cover",
        "loose textile spread with soft folds",
        "warm cover casually draped",
    ],
    "sculpture": [
        "carved or cast three-dimensional artwork",
        "stone or metal figure on display",
        "abstract or figurative solid art piece",
        "modeled artistic form on a plinth",
        "chiseled decorative figure",
        "solid artwork with sculpted contours",
    ],
    "hood": [
        "metal exhaust canopy above a stove",
        "kitchen extractor with a vent",
        "sloped steel fume collector",
        "range hood with a filter and light",
        "overhead suction unit above burners",
        "angled vent housing over a cooktop",
    ],
    "sconce": [
        "light fixture mounted on a wall",
        "decorative bracket lamp",
        "wall-arm light with a small shade",
        "fixed side light beside a mirror",
        "ornamental wall-mounted lamp",
        "upward-glowing wall light",
    ],
    "vase": [
        "decorative vessel for cut flowers",
        "slender ceramic or glass container",
        "curved ornamental jar with a narrow neck",
        "tabletop vessel holding stems",
        "glazed decorative flask",
        "elegant container with a flared mouth",
    ],
    "traffic light": [
        "signal with red, yellow and green lamps",
        "pole-mounted stoplight at a junction",
        "stacked colored lights controlling traffic",
        "hanging signal head over an intersection",
        "three-lens roadway signal",
        "glowing traffic control lamps",
    ],
    "tray": [
        "flat shallow carrier with raised edges",
        "rectangular serving board with a lip",
        "portable flat platter for dishes",
        "shallow rimmed carrying surface",
        "serving slab balanced by hand",
        "flat holder for cups and plates",
    ],
    "ashcan": [
        "metal refuse bin with a lid",
        "cylindrical trash container",
        "street rubbish can",
        "dented garbage container outdoors",
        "waste bin with a swing or open top",
        "utilitarian refuse drum",
    ],
    "fan": [
        "bladed device that circulates air",
        "rotating blades in a round cage",
        "ceiling or standing air mover",
        "spinning propeller-like cooling device",
        "electric device with whirling blades",
        "portable air circulator with a grille",
    ],
    "pier": [
        "wooden walkway extending over water",
        "raised deck on pilings above the sea",
        "long boardwalk jutting from the shore",
        "planked platform standing on posts in water",
        "dock structure stretching into a lake",
        "stilted promenade above the waves",
    ],
    "crt screen": [
        "bulky deep-bodied monitor",
        "curved glass display with a thick back",
        "boxy old television tube",
        "heavy vintage monitor casing",
        "convex glowing screen in a deep shell",
        "retro display with a rounded glass front",
    ],
    "plate": [
        "round flat dish for serving food",
        "ceramic circle with a raised rim",
        "shallow dinner dish",
        "glazed round tableware piece",
        "flat circular dish on a table",
        "clean white dish with a smooth rim",
    ],
    "monitor": [
        "thin computer display on a stand",
        "flat rectangular screen with bezels",
        "desktop display showing content",
        "sleek panel screen at eye level",
        "widescreen display beside a keyboard",
        "slim glowing display on a desk",
    ],
    "bulletin board": [
        "cork panel pinned with notices",
        "wall board covered in papers",
        "notice surface with tacked flyers",
        "framed board layered with announcements",
        "pinboard crowded with notes",
        "public posting panel with sheets",
    ],
    "shower": [
        "tiled stall with an overhead spray",
        "glass-enclosed washing area",
        "bathroom corner with a shower head",
        "wet cubicle with a drain and faucet",
        "spraying fixture above a tiled base",
        "enclosed standing wash space",
    ],
    "radiator": [
        "ribbed metal heating unit under a window",
        "finned panel radiating warmth",
        "wall-mounted hot-water heater body",
        "sectioned metal heater with valves",
        "corrugated heating element indoors",
        "painted metal ribs emitting heat",
    ],
    "glass": [
        "clear drinking vessel",
        "transparent cup without a handle",
        "slender tumbler holding liquid",
        "shiny clear beverage container",
        "thin-walled transparent cup",
        "stemmed or straight clear drinkware",
    ],
    "clock": [
        "round face with moving hands",
        "timepiece with numerals on a dial",
        "wall-mounted circular time display",
        "ticking instrument showing the hour",
        "framed dial with hour and minute hands",
        "analog or digital time indicator",
    ],
    "flag": [
        "colored cloth waving on a pole",
        "rectangular banner in the wind",
        "patterned fabric hoisted high",
        "national or decorative pennant",
        "fluttering textile on a mast",
        "bright banner fixed at one edge",
    ],
}
